version: '3'
services: 
  postgres:
    container_name: 'postgres'
    image: postgres:9.4
    ports:
      - '5432:5432'
    environment: 
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes: 
      - ./postgres_data:/var/lib/postgresql/data
  mongo:
    container_name: 'mongo'
    image: mongo:latest
    restart: always
    environment:
      PUID: 1000
      PGID: 1000
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db
  category-api:
    environment: 
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    container_name: category-api
    build: ./backend/categoryAPI
    ports: 
      - 5000:5000
    depends_on:
      - postgres
  product-api:
    environment: 
      category_url: http://category-api:5000
      hostURL: mongo
    container_name: product-api
    build: ./backend/productAPI
    ports:
      - 5001:5001
    depends_on:
      - mongo
      - category-api
