version: "3.9"
services: 
  postgres:
    container_name: 'postgres'
    image: postgres:9.4
    networks:
      - mynet
    ports:
      - '5432:5432'
    environment: 
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes: 
      - ./postgres_data:/var/lib/postgresql/data
  mongo:
    container_name: 'mongo'
    image: mongo:latest
    restart: always
    networks:
        - mynet
    environment:
      PUID: 1000
      PGID: 1000
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db
  category-api-service:
    environment: 
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    container_name: category-api-service
    image: category-api:latest
    networks:
      - mynet
    build: ./backend/categoryAPI
    ports: 
      - 5000:5000
    depends_on:
      - postgres
  product-api-service:
    environment: 
      category_url: http://category-api-service:5000
      hostURL: mongo
    container_name: product-api-service
    build: ./backend/productAPI
    image: product-api:latest
    networks:
      - mynet
    ports:
      - 5001:5001
    depends_on:
      - mongo
      - category-api-service
  frontend-application:
    container_name: frontend-application
    build: ./frontend
    image: frontend-application:latest
    environment: 
      category_service_url: http://localhost:5000
      product_service_url: http://localhost:5001
    ports:
      - 80:80
    networks:
      - mynet
    depends_on:
      - product-api-service
      - category-api-service
networks:
  mynet:
