apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: frontend-application
    version: v1
  name: frontend-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-application
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend-application
        version: v1
    spec:
      containers:
      - image: frontend-application:latest
        name: frontend-application
        livenessProbe:
          httpGet:
            path: /
            port: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: category_service_url
          value: http://localhost/apic
        - name: product_service_url
          value: http://localhost/apip
