apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: frontend-service
  name: frontend-service
spec:
  ports:
  - name: http
    nodePort: 30083
    port: 80
    targetPort: 80
  selector:
    app: frontend-application
  type: NodePort
status:
  loadBalancer: {}
