apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: frontend-service
  name: frontend-service
spec:
  ports:
  - name:  tcp-80
    nodePort: 30083
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend-application
  type: NodePort
status:
  loadBalancer: {}
