apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: category-api
  name: category-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: category-api
  template:
    metadata:
      labels:
        app: category-api
    spec:
      containers:
      - image: category-api
        name: category-api
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: POSTGRES_HOST
          value: postgres
        - name: POSTGRES_PORT
          value: "5432"
