apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: category-api-service
spec:
  defaultBackend:
    service:
      name: category-api-service
      port:
        number: 5000

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: category-ingress-service
spec:
  rules:
  - host: category-api-service
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: category-api-service
            port:
              number: 80
  - host: bar.foo.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: service2
            port:
              number: 80