apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: category-api-service
  name: category-api-service
spec:
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    nodePort: 30091
  selector:
    app: category-api
  type: NodePort

