kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: sample-webapp
spec:
  hosts:      # which incoming host are we applying the proxy rules to???
    - "*"
  gateways:
    - sample-app
  http:
    - route:
      - destination:
          host: frontend-service
          port:
            number: 80
