apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservice-ingress-service
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /apic/?(.*)
        backend:
          service:
            name: category-api-service
            port:
              number: 5000
      - pathType: Prefix
        path: /apip/?(.*) 
        backend:
          service:
            name: product-api-service
            port:
              number: 5001
      - pathType: Prefix
        path: /?(.*) 
        backend:
          service:
            name: frontend-service
            port:
              number: 80
