apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: product-api-service
  name: product-api-service
spec:
  ports:
  - name: http
    port: 5001
    targetPort: 5001
    nodePort: 30092
  selector:
    app: product-api
  type: NodePort
