apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AyushSoni-7/microservices-k8s.git
    targetRevision: main
    path: argocd/applications 
  destination:
    server: https://kubernetes.default.svc
    namespace: default

