apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: category-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/AyushSoni-7/microservices-k8s.git
    targetRevision: main
    path: k8s/category-api 
  destination:
    server: https://kubernetes.default.svc
    namespace: default

