apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/AyushSoni-7/microservices-k8s.git
    targetRevision: feature-istio-service-mesh
    path: k8s/product-api 
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

